### ISSUE TITLE
Rename `include` and `notInclude` to `contains` and `notContains`

### ISSUE THREAD

**Issue by drapergeek** [thoughtbot/ember-tb-test-helpers#12]
I think I'm responsible for naming those helpers but unfortunately, they don't follow the ember naming which uses `contains`.

Should we rename those to follow the Ember enumerable methods?

If so I'm happy to drop a PR, just wanted to get other opinions before charing forward.

**Comment by seanpdoyle** [comment]
:+1: 

We could also alias them:

``` js
assert.contains = assert.includes;
```

We could discuss that in the PR with the code.
